GET http://localhost:2003/api/companies HTTP/1.1

###Post Test
POST http://localhost:2003/api/companies HTTP/1.1
Content-Type: application/json

{
    "company_name" : "PT Semesta Karya Permanent",
    "telephone_number" : "083123",
    "address" : "Jl jalan"
}

###PUT Test
PUT http://localhost:2003/api/companies/2/set_active HTTP/1.1


###ADDemployee Test
POST http://localhost:2003/api/companies/2/employees HTTP/1.1
Content-Type: application/json

{
    "name" : "Karyawan Params",
    "email" : "araarara@ara",
    "phone_number" : "08312312",
    "jobtitle" : "manager",
    "company_id": 2
}
###GET Test Employee by Company Id
GET http://localhost:2003/api/companies/1/employees HTTP/1.1

###GET Test Single Employee
GET http://localhost:2003/api/employees/2 HTTP/1.1

###Update Employee
PUT http://localhost:2003/api/companies/3/employees/3 HTTP/1.1
Content-Type: application/json

{
    "name" : "Karyawan Update",
    "phone_number" : "666",
    "jobtitle" : "director"
}

###Delete Test Single Employee
DELETE  http://localhost:2003/api/employees/4 HTTP/1.1

###GET Test Countries
GET http://localhost:2003/api/countries HTTP/1.1
Content-Type: application/json

###GET Test Fibonacci
POST http://localhost:2003/api/fibonacci HTTP/1.1
Content-Type: application/json

{
    "n" : "dasda"
}

###GET Test Combination
POST http://localhost:2003/api/combination HTTP/1.1
Content-Type: application/json

{
    "n" : 4,
    "r" : 2
}